prompt PL/SQL Developer import file
prompt Created on martes, 13 de julio de 2010 by mjara
set feedback off
set define off
prompt Dropping BANCO...
drop table BANCO cascade constraints;
prompt Dropping CAB...
drop table CAB cascade constraints;
prompt Dropping CABECERA...
drop table CABECERA cascade constraints;
prompt Dropping CAJA...
drop table CAJA cascade constraints;
prompt Dropping CARGO...
drop table CARGO cascade constraints;
prompt Dropping CIUDAD...
drop table CIUDAD cascade constraints;
prompt Dropping CLIENTE...
drop table CLIENTE cascade constraints;
prompt Dropping TIPO_PRODUCTO...
drop table TIPO_PRODUCTO cascade constraints;
prompt Dropping UNIDAD_MEDIDA...
drop table UNIDAD_MEDIDA cascade constraints;
prompt Dropping MARCA...
drop table MARCA cascade constraints;
prompt Dropping PRESENTACION...
drop table PRESENTACION cascade constraints;
prompt Dropping PRODUCTO...
drop table PRODUCTO cascade constraints;
prompt Dropping COMISION...
drop table COMISION cascade constraints;
prompt Dropping SECCION...
drop table SECCION cascade constraints;
prompt Dropping EMPLEADO...
drop table EMPLEADO cascade constraints;
prompt Dropping COMISION_MENS_CAB...
drop table COMISION_MENS_CAB cascade constraints;
prompt Dropping COMISION_MENS_DET...
drop table COMISION_MENS_DET cascade constraints;
prompt Dropping ORDEN_TRABAJO...
drop table ORDEN_TRABAJO cascade constraints;
prompt Dropping ORDEN_TRABAJO_DETALLE...
drop table ORDEN_TRABAJO_DETALLE cascade constraints;
prompt Dropping COSTOS_FIJOS...
drop table COSTOS_FIJOS cascade constraints;
prompt Dropping DEPOSITO...
drop table DEPOSITO cascade constraints;
prompt Dropping DET...
drop table DET cascade constraints;
prompt Dropping DETALLE...
drop table DETALLE cascade constraints;
prompt Dropping DET2...
drop table DET2 cascade constraints;
prompt Dropping ENTRADA_SALIDA_CABECERA...
drop table ENTRADA_SALIDA_CABECERA cascade constraints;
prompt Dropping SOLICITUD_INTERNA...
drop table SOLICITUD_INTERNA cascade constraints;
prompt Dropping ENTRADA_SALIDA_DETALLE...
drop table ENTRADA_SALIDA_DETALLE cascade constraints;
prompt Dropping EQUIVALENCIA...
drop table EQUIVALENCIA cascade constraints;
prompt Dropping EXISTENCIA...
drop table EXISTENCIA cascade constraints;
prompt Dropping TIPO_COMPROBANTE...
drop table TIPO_COMPROBANTE cascade constraints;
prompt Dropping PEDIDO_CABECERA...
drop table PEDIDO_CABECERA cascade constraints;
prompt Dropping FACTURA_CABECERA...
drop table FACTURA_CABECERA cascade constraints;
prompt Dropping PROVEEDOR...
drop table PROVEEDOR cascade constraints;
prompt Dropping FACTURA_COMPRA_CAB...
drop table FACTURA_COMPRA_CAB cascade constraints;
prompt Dropping FACTURA_COMPRA_DET...
drop table FACTURA_COMPRA_DET cascade constraints;
prompt Dropping PEDIDO_DETALLE...
drop table PEDIDO_DETALLE cascade constraints;
prompt Dropping FACTURA_DETALLE...
drop table FACTURA_DETALLE cascade constraints;
prompt Dropping FORMA_PAGO...
drop table FORMA_PAGO cascade constraints;
prompt Dropping FORMULA_CABECERA...
drop table FORMULA_CABECERA cascade constraints;
prompt Dropping FORMULA_DETALLE...
drop table FORMULA_DETALLE cascade constraints;
prompt Dropping FORMULA_SEMI_CABECERA...
drop table FORMULA_SEMI_CABECERA cascade constraints;
prompt Dropping FORMULA_SEMI_DETALLE...
drop table FORMULA_SEMI_DETALLE cascade constraints;
prompt Dropping HABILITACION_CAJA...
drop table HABILITACION_CAJA cascade constraints;
prompt Dropping GASTO...
drop table GASTO cascade constraints;
prompt Dropping HISTORICO_COSTO...
drop table HISTORICO_COSTO cascade constraints;
prompt Dropping HISTORICO_PRECIO...
drop table HISTORICO_PRECIO cascade constraints;
prompt Dropping INVENTARIO_CABECERA...
drop table INVENTARIO_CABECERA cascade constraints;
prompt Dropping INVENTARIO_DETALLE...
drop table INVENTARIO_DETALLE cascade constraints;
prompt Dropping RECIBO_CABECERA...
drop table RECIBO_CABECERA cascade constraints;
prompt Dropping MOVIMIENTO_CAJA_CABECERA...
drop table MOVIMIENTO_CAJA_CABECERA cascade constraints;
prompt Dropping MOVIMIENTO_CAJA_DETALLE...
drop table MOVIMIENTO_CAJA_DETALLE cascade constraints;
prompt Dropping NOTA_CREDITO_CLI_CABECERA...
drop table NOTA_CREDITO_CLI_CABECERA cascade constraints;
prompt Dropping NOTA_CREDITO_CLI_DETALLE...
drop table NOTA_CREDITO_CLI_DETALLE cascade constraints;
prompt Dropping NOTA_CREDITO_PROV_CAB...
drop table NOTA_CREDITO_PROV_CAB cascade constraints;
prompt Dropping NOTA_CREDITO_PROV_DET...
drop table NOTA_CREDITO_PROV_DET cascade constraints;
prompt Dropping ORDEN_TRABAJO_DET_COSTO_H...
drop table ORDEN_TRABAJO_DET_COSTO_H cascade constraints;
prompt Dropping ORDEN_TRABAJO_DET_COSTO_MAT...
drop table ORDEN_TRABAJO_DET_COSTO_MAT cascade constraints;
prompt Dropping PERDIDA...
drop table PERDIDA cascade constraints;
prompt Dropping TAREA...
drop table TAREA cascade constraints;
prompt Dropping TAREA_ASIGNADA...
drop table TAREA_ASIGNADA cascade constraints;
prompt Dropping PRODUCCION_DIARIA...
drop table PRODUCCION_DIARIA cascade constraints;
prompt Dropping RECIBO_DETALLE...
drop table RECIBO_DETALLE cascade constraints;
prompt Dropping RECURSO_ASIGNADO...
drop table RECURSO_ASIGNADO cascade constraints;
prompt Dropping SALDO_CLIENTE...
drop table SALDO_CLIENTE cascade constraints;
prompt Dropping TAREA_FORMULA...
drop table TAREA_FORMULA cascade constraints;

prompt 15 records loaded
prompt Loading TAREA_FORMULA...
prompt Table is empty
set feedback on
set define on
prompt Done.
